"use client";

import {
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useState,
  type FormEvent,
} from "react";
import Link from "next/link";
import {
  Archive,
  ArchiveRestore,
  Bell,
  BellOff,
  CheckCheck,
  Clock,
  Eye,
  EyeOff,
  Filter,
  Inbox,
  Loader2,
  RefreshCw,
  Search,
  Settings,
  Sliders,
  Trash2,
  X,
} from "lucide-react";
import { cn } from "@/lib/utils";
import { useSession } from "next-auth/react";
import {
  useRealtimeEvent,
  type NotificationPayload,
} from "@/lib/realtime/client";
import { PageHeader } from "@/components/ui/PageHeader";
import { NotificationIcon, colorFor } from "./NotificationIcon";
import {
  CATEGORY_LABELS,
  type EventCategory,
} from "@/lib/notifications/events";

interface NotificationRow {
  id: number;
  userId: number;
  type: string;
  title: string;
  body: string | null;
  linkUrl: string | null;
  payloadJson: unknown;
  category: string | null;
  priority: number;
  readAt: string | null;
  archivedAt: string | null;
  snoozedUntil: string | null;
  createdAt: string;
}

interface ListResponse {
  items: NotificationRow[];
  unreadCount: number;
  totalCount: number;
  nextCursor: number | null;
}

type Tab = "all" | "unread" | "important" | "archived";

const TABS: { key: Tab; label: string; icon: typeof Bell }[] = [
  { key: "all", label: "الكل", icon: Inbox },
  { key: "unread", label: "غير المقروءة", icon: Bell },
  { key: "important", label: "مهم", icon: BellOff },
  { key: "archived", label: "الأرشيف", icon: Archive },
];

const PRIORITY_LABEL: Record<number, string> = {
  0: "عادية",
  1: "مرتفعة",
  2: "عاجل",
};

/**
 * Ensure URLs that look like external paths get prefixed properly. Internal
 * link URLs stored on a notification almost always begin with "/" but we
 * defend against the rare http:// link generated by older code.
 */
function normalizeHref(url: string | null): string | null {
  if (!url) return null;
  if (url.startsWith("http")) return url;
  if (!url.startsWith("/")) return `/${url}`;
  return url;
}

/**
 * NotificationCenter — full-page notification inbox.
 *
 * UX surface:
 *   - Header with hero title + total badge + buttons (refresh, preferences,
 *     mark-all-read).
 *   - Tab strip (الكل / غير المقروءة / المهم / الأرشيف).
 *   - Toolbar (search, category select, priority select).
 *   - Day-grouped list (اليوم / الأمس / هذا الأسبوع / أقدم).
 *   - Per-row actions (read/unread, snooze 1h, archive/restore, delete).
 *   - Multi-select toolbar with bulk read / archive.
 */
export function NotificationCenter() {
  const { status } = useSession();
  const [items, setItems] = useState<NotificationRow[]>([]);
  const [unreadCount, setUnreadCount] = useState(0);
  const [totalCount, setTotalCount] = useState(0);
  const [tab, setTab] = useState<Tab>("all");
  const [q, setQ] = useState("");
  const [category, setCategory] = useState<string>("");
  const [minPriority, setMinPriority] = useState<string>("");
  const [loading, setLoading] = useState(false);
  const [bulkBusy, setBulkBusy] = useState(false);
  const [selected, setSelected] = useState<Set<number>>(new Set());
  const [error, setError] = useState<string | null>(null);
  const debounceRef = useRef<number | null>(null);

  const buildQuery = useCallback(() => {
    const sp = new URLSearchParams();
    sp.set("limit", "100");
    if (tab === "unread") sp.set("unreadOnly", "true");
    if (tab === "archived") sp.set("archived", "true");
    if (tab !== "archived") sp.set("archived", "false");
    if (tab === "important") sp.set("priority", "1");
    if (q.trim()) sp.set("q", q.trim());
    if (category) sp.set("category", category);
    if (minPriority) sp.set("priority", minPriority);
    return sp.toString();
  }, [tab, q, category, minPriority]);

  const load = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const res = await fetch(`/api/notifications?${buildQuery()}`, {
        cache: "no-store",
      });
      if (!res.ok) {
        const data = await res.json().catch(() => ({}));
        throw new Error(data?.error || "فشل التحميل");
      }
      const data: ListResponse = await res.json();
      setItems(data.items || []);
      setUnreadCount(data.unreadCount || 0);
      setTotalCount(data.totalCount || 0);
      setSelected(new Set());
    } catch (e) {
      setError(e instanceof Error ? e.message : "فشل التحميل");
    } finally {
      setLoading(false);
    }
  }, [buildQuery]);

  useEffect(() => {
    if (status !== "authenticated") return;
    if (debounceRef.current) window.clearTimeout(debounceRef.current);
    debounceRef.current = window.setTimeout(() => load(), 200);
    return () => {
      if (debounceRef.current) window.clearTimeout(debounceRef.current);
    };
  }, [load, status]);

  // Real-time refresh — when a new notification arrives, refresh both
  // the list and the badge counters so the user sees it appear live.
  useRealtimeEvent<NotificationPayload>(
    "notification:new",
    () => {
      load();
    },
    [load],
  );

  // Listen to the cross-component "I marked these read" event so badges
  // and the bell stay in sync after the WhatsApp inbox clears messages.
  useEffect(() => {
    const handler = () => load();
    window.addEventListener("notifications:changed", handler);
    return () => window.removeEventListener("notifications:changed", handler);
  }, [load]);

  // ─── Mutations ───────────────────────────────────────────────
  const patchOne = useCallback(
    async (id: number, body: { read?: boolean; archived?: boolean }) => {
      const res = await fetch(`/api/notifications/${id}`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      });
      if (!res.ok) throw new Error("فشل التحديث");
    },
    [],
  );

  const snoozeOne = useCallback(async (id: number, minutes: number) => {
    const res = await fetch(`/api/notifications/${id}/snooze`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ minutes }),
    });
    if (!res.ok) throw new Error("فشل التأجيل");
  }, []);

  const deleteOne = useCallback(async (id: number) => {
    const res = await fetch(`/api/notifications/${id}`, {
      method: "DELETE",
    });
    if (!res.ok) throw new Error("فشل الحذف");
  }, []);

  const toggleRead = useCallback(
    async (row: NotificationRow) => {
      try {
        const next = !row.readAt;
        setItems((prev) =>
          prev.map((n) =>
            n.id === row.id
              ? { ...n, readAt: next ? new Date().toISOString() : null }
              : n,
          ),
        );
        setUnreadCount((u) => Math.max(0, u + (next ? -1 : 1)));
        await patchOne(row.id, { read: next });
        window.dispatchEvent(new CustomEvent("notifications:changed"));
      } catch {
        load();
      }
    },
    [load, patchOne],
  );

  const toggleArchive = useCallback(
    async (row: NotificationRow) => {
      try {
        const next = !row.archivedAt;
        setItems((prev) =>
          prev.filter((n) => n.id !== row.id || tab === "archived"),
        );
        await patchOne(row.id, { archived: next });
        window.dispatchEvent(new CustomEvent("notifications:changed"));
        // re-load to reflect counts on archive tab
        if (tab === "archived") load();
      } catch {
        load();
      }
    },
    [load, patchOne, tab],
  );

  const snoozeFor = useCallback(
    async (row: NotificationRow, minutes: number) => {
      try {
        setItems((prev) => prev.filter((n) => n.id !== row.id));
        await snoozeOne(row.id, minutes);
        window.dispatchEvent(new CustomEvent("notifications:changed"));
      } catch {
        load();
      }
    },
    [load, snoozeOne],
  );

  const removeRow = useCallback(
    async (row: NotificationRow) => {
      if (!confirm("حذف هذا الإشعار نهائيًا؟")) return;
      try {
        setItems((prev) => prev.filter((n) => n.id !== row.id));
        await deleteOne(row.id);
        window.dispatchEvent(new CustomEvent("notifications:changed"));
      } catch {
        load();
      }
    },
    [deleteOne, load],
  );

  const markAllRead = useCallback(async () => {
    setBulkBusy(true);
    try {
      await fetch("/api/notifications/bulk", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          action: "read",
          all: true,
          filter: { unreadOnly: true },
        }),
      });
      window.dispatchEvent(new CustomEvent("notifications:changed"));
      await load();
    } finally {
      setBulkBusy(false);
    }
  }, [load]);

  const bulkAction = useCallback(
    async (action: "read" | "archive") => {
      if (!selected.size) return;
      setBulkBusy(true);
      try {
        await fetch("/api/notifications/bulk", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ action, ids: Array.from(selected) }),
        });
        setSelected(new Set());
        window.dispatchEvent(new CustomEvent("notifications:changed"));
        await load();
      } finally {
        setBulkBusy(false);
      }
    },
    [load, selected],
  );

  const onSearchSubmit = useCallback(
    (e: FormEvent<HTMLFormElement>) => {
      e.preventDefault();
      load();
    },
    [load],
  );

  // ─── Group by day ────────────────────────────────────────────
  const groups = useMemo(() => {
    const today = new Date();
    today.setHours(0, 0, 0, 0);
    const yesterday = new Date(today);
    yesterday.setDate(yesterday.getDate() - 1);
    const weekAgo = new Date(today);
    weekAgo.setDate(weekAgo.getDate() - 7);

    const buckets: Record<string, NotificationRow[]> = {
      today: [],
      yesterday: [],
      week: [],
      older: [],
    };
    for (const n of items) {
      const d = new Date(n.createdAt);
      if (d >= today) buckets.today.push(n);
      else if (d >= yesterday) buckets.yesterday.push(n);
      else if (d >= weekAgo) buckets.week.push(n);
      else buckets.older.push(n);
    }
    return buckets;
  }, [items]);

  const dayLabels: Record<string, string> = {
    today: "اليوم",
    yesterday: "الأمس",
    week: "هذا الأسبوع",
    older: "أقدم",
  };

  const tabCount = useCallback(
    (which: Tab) => {
      switch (which) {
        case "unread":
          return unreadCount;
        case "all":
          return totalCount;
        default:
          return undefined;
      }
    },
    [totalCount, unreadCount],
  );

  if (status !== "authenticated") {
    return (
      <div className="bg-card-bg rounded-xl shadow-sm p-12 text-center text-gray-400">
        يجب تسجيل الدخول لعرض الإشعارات.
      </div>
    );
  }

  return (
    <>
      <PageHeader
        title="مركز الإشعارات"
        description="جميع التنبيهات في مكان واحد — اقرأ، أرشف، أجِّل، أو خصِّص ما يصلك."
        icon={<Bell size={22} />}
        actions={
          <div className="flex flex-wrap items-center gap-2">
            <button
              onClick={() => load()}
              className="tap-44 flex items-center gap-1.5 text-sm px-3 py-2 border border-gray-200 rounded-lg hover:bg-gray-50"
              aria-label="تحديث"
            >
              <RefreshCw
                size={14}
                className={cn(loading && "animate-spin")}
              />
              تحديث
            </button>
            <button
              onClick={markAllRead}
              disabled={bulkBusy || unreadCount === 0}
              className="tap-44 flex items-center gap-1.5 text-sm px-3 py-2 bg-primary text-white rounded-lg hover:bg-primary-dark disabled:opacity-50"
            >
              <CheckCheck size={14} />
              تعليم الكل مقروء
            </button>
            <Link
              href="/notifications/preferences"
              className="tap-44 flex items-center gap-1.5 text-sm px-3 py-2 border border-gray-200 rounded-lg hover:bg-gray-50"
            >
              <Settings size={14} />
              التفضيلات
            </Link>
          </div>
        }
      />

      {/* ─── Stats strip ─────────────────────────────────────── */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
        <StatCard
          icon={<Inbox size={18} />}
          label="إجمالي الإشعارات"
          value={totalCount}
          color="#7367f0"
        />
        <StatCard
          icon={<Bell size={18} />}
          label="غير مقروءة"
          value={unreadCount}
          color="#ea5455"
        />
        <StatCard
          icon={<Archive size={18} />}
          label="عرض حالي"
          value={items.length}
          color="#00cfe8"
        />
        <StatCard
          icon={<Sliders size={18} />}
          label="القنوات الفعّالة"
          color="#28c76f"
          link={{ href: "/notifications/preferences", label: "تخصيص" }}
        />
      </div>

      {/* ─── Tabs ────────────────────────────────────────────── */}
      <div className="bg-card-bg rounded-xl shadow-sm overflow-hidden">
        <div className="flex flex-wrap items-stretch border-b border-gray-100">
          {TABS.map((t) => {
            const Icon = t.icon;
            const c = tabCount(t.key);
            const active = tab === t.key;
            return (
              <button
                key={t.key}
                onClick={() => setTab(t.key)}
                className={cn(
                  "tap-44 flex-1 min-w-[120px] flex items-center justify-center gap-2 text-sm font-medium px-3 py-3 border-b-2 transition-colors",
                  active
                    ? "border-primary text-primary bg-primary/5"
                    : "border-transparent text-gray-600 hover:bg-gray-50",
                )}
                role="tab"
                aria-selected={active}
              >
                <Icon size={16} />
                <span>{t.label}</span>
                {typeof c === "number" && c > 0 && (
                  <span
                    className={cn(
                      "min-w-[20px] px-1.5 h-5 rounded-full text-[10px] font-bold flex items-center justify-center",
                      active
                        ? "bg-primary text-white"
                        : "bg-gray-100 text-gray-600",
                    )}
                  >
                    {c}
                  </span>
                )}
              </button>
            );
          })}
        </div>

        {/* ─── Filter toolbar ──────────────────────────────── */}
        <form
          onSubmit={onSearchSubmit}
          className="flex flex-wrap items-center gap-2 px-3 py-3 border-b border-gray-100 bg-gray-50/40"
        >
          <div className="relative flex-1 min-w-[180px]">
            <Search
              size={14}
              className="absolute top-1/2 -translate-y-1/2 start-3 text-gray-400 pointer-events-none"
            />
            <input
              type="search"
              value={q}
              onChange={(e) => setQ(e.target.value)}
              placeholder="بحث في العنوان أو المحتوى..."
              className="w-full ps-9 pe-3 py-2 text-sm border border-gray-200 rounded-lg bg-white focus:outline-none focus:ring-2 focus:ring-primary/20"
            />
          </div>
          <select
            value={category}
            onChange={(e) => setCategory(e.target.value)}
            className="px-3 py-2 text-sm border border-gray-200 rounded-lg bg-white focus:outline-none focus:ring-2 focus:ring-primary/20"
            aria-label="التصنيف"
          >
            <option value="">كل التصنيفات</option>
            {(Object.keys(CATEGORY_LABELS) as EventCategory[]).map((c) => (
              <option key={c} value={c}>
                {CATEGORY_LABELS[c].label}
              </option>
            ))}
          </select>
          <select
            value={minPriority}
            onChange={(e) => setMinPriority(e.target.value)}
            className="px-3 py-2 text-sm border border-gray-200 rounded-lg bg-white focus:outline-none focus:ring-2 focus:ring-primary/20"
            aria-label="الأولوية"
          >
            <option value="">كل الأولويات</option>
            <option value="2">عاجل فقط</option>
            <option value="1">مرتفعة فأعلى</option>
            <option value="0">الكل</option>
          </select>
          {(q || category || minPriority) && (
            <button
              type="button"
              onClick={() => {
                setQ("");
                setCategory("");
                setMinPriority("");
              }}
              className="tap-44 flex items-center gap-1 text-sm px-3 py-2 border border-gray-200 rounded-lg hover:bg-white"
            >
              <X size={14} />
              مسح
            </button>
          )}
          <button
            type="submit"
            className="tap-44 flex items-center gap-1.5 text-sm px-3 py-2 bg-primary/10 text-primary rounded-lg hover:bg-primary/20"
          >
            <Filter size={14} />
            تطبيق
          </button>
        </form>

        {/* ─── Selection bar ───────────────────────────────── */}
        {selected.size > 0 && (
          <div className="flex flex-wrap items-center gap-2 px-3 py-2 border-b border-amber-200 bg-amber-50">
            <span className="text-sm font-semibold text-amber-800">
              {selected.size} محدّد
            </span>
            <button
              onClick={() => bulkAction("read")}
              disabled={bulkBusy}
              className="tap-44 flex items-center gap-1 text-sm px-2.5 py-1.5 border border-amber-300 rounded-lg hover:bg-white disabled:opacity-50"
            >
              <Eye size={13} />
              تعليم مقروء
            </button>
            <button
              onClick={() => bulkAction("archive")}
              disabled={bulkBusy}
              className="tap-44 flex items-center gap-1 text-sm px-2.5 py-1.5 border border-amber-300 rounded-lg hover:bg-white disabled:opacity-50"
            >
              <Archive size={13} />
              أرشفة
            </button>
            <button
              onClick={() => setSelected(new Set())}
              className="tap-44 flex items-center gap-1 text-sm px-2.5 py-1.5 hover:bg-white rounded-lg ms-auto"
            >
              <X size={13} />
              إلغاء التحديد
            </button>
          </div>
        )}

        {/* ─── Body ────────────────────────────────────────── */}
        {loading ? (
          <div className="py-16 flex justify-center">
            <Loader2 size={24} className="animate-spin text-primary" />
          </div>
        ) : error ? (
          <div className="py-12 text-center text-sm text-red-600">{error}</div>
        ) : items.length === 0 ? (
          <EmptyState tab={tab} />
        ) : (
          <div className="divide-y divide-gray-100">
            {(["today", "yesterday", "week", "older"] as const).map((key) => {
              const list = groups[key];
              if (!list.length) return null;
              return (
                <section key={key} className="py-2">
                  <h3 className="px-4 py-2 text-[11px] font-bold text-gray-500 uppercase tracking-wide">
                    {dayLabels[key]} · {list.length}
                  </h3>
                  <ul role="list" className="divide-y divide-gray-100">
                    {list.map((n) => (
                      <NotificationRowItem
                        key={n.id}
                        row={n}
                        selected={selected.has(n.id)}
                        onToggleSelect={(checked) =>
                          setSelected((prev) => {
                            const next = new Set(prev);
                            if (checked) next.add(n.id);
                            else next.delete(n.id);
                            return next;
                          })
                        }
                        onToggleRead={() => toggleRead(n)}
                        onToggleArchive={() => toggleArchive(n)}
                        onSnooze={(minutes) => snoozeFor(n, minutes)}
                        onDelete={() => removeRow(n)}
                      />
                    ))}
                  </ul>
                </section>
              );
            })}
          </div>
        )}
      </div>
    </>
  );
}

function StatCard({
  icon,
  label,
  value,
  color,
  link,
}: {
  icon: React.ReactNode;
  label: string;
  value?: number;
  color: string;
  link?: { href: string; label: string };
}) {
  return (
    <div
      className="bg-card-bg rounded-xl shadow-sm p-3 sm:p-4 border-l-4"
      style={{ borderLeftColor: color }}
    >
      <div className="flex items-center justify-between gap-2">
        <span
          className="shrink-0 w-9 h-9 rounded-lg flex items-center justify-center"
          style={{ backgroundColor: `${color}15`, color }}
        >
          {icon}
        </span>
        {typeof value === "number" && (
          <span className="text-2xl font-bold text-gray-800">{value}</span>
        )}
      </div>
      <div className="mt-2 text-xs text-gray-500 font-medium">{label}</div>
      {link && (
        <Link
          href={link.href}
          className="mt-1 inline-block text-xs text-primary hover:underline"
        >
          {link.label} ←
        </Link>
      )}
    </div>
  );
}

function EmptyState({ tab }: { tab: Tab }) {
  const labels: Record<Tab, { title: string; hint: string }> = {
    all: {
      title: "لا توجد إشعارات",
      hint: "ستظهر هنا كل التنبيهات المتعلقة بحسابك.",
    },
    unread: {
      title: "تم تنظيم صندوق الوارد",
      hint: "لا يوجد إشعار غير مقروء حاليًا.",
    },
    important: {
      title: "لا إشعارات مهمة",
      hint: "الإشعارات ذات الأولوية المرتفعة والعاجلة ستظهر هنا.",
    },
    archived: {
      title: "الأرشيف فارغ",
      hint: "أرشف الإشعارات لإزالتها من الصندوق دون حذفها.",
    },
  };
  const l = labels[tab];
  return (
    <div className="py-16 text-center">
      <div className="w-14 h-14 mx-auto rounded-full bg-gray-100 text-gray-400 flex items-center justify-center mb-3">
        <BellOff size={22} />
      </div>
      <p className="text-sm font-bold text-gray-700">{l.title}</p>
      <p className="text-xs text-gray-400 mt-1">{l.hint}</p>
    </div>
  );
}

function NotificationRowItem({
  row,
  selected,
  onToggleSelect,
  onToggleRead,
  onToggleArchive,
  onSnooze,
  onDelete,
}: {
  row: NotificationRow;
  selected: boolean;
  onToggleSelect: (checked: boolean) => void;
  onToggleRead: () => void;
  onToggleArchive: () => void;
  onSnooze: (minutes: number) => void;
  onDelete: () => void;
}) {
  const color = colorFor(row.category);
  const isUnread = !row.readAt;
  const isArchived = !!row.archivedAt;
  const href = normalizeHref(row.linkUrl);
  const [snoozeOpen, setSnoozeOpen] = useState(false);
  const snoozeRef = useRef<HTMLDivElement | null>(null);

  useEffect(() => {
    if (!snoozeOpen) return;
    function onDown(e: MouseEvent) {
      if (snoozeRef.current && !snoozeRef.current.contains(e.target as Node)) {
        setSnoozeOpen(false);
      }
    }
    document.addEventListener("mousedown", onDown);
    return () => document.removeEventListener("mousedown", onDown);
  }, [snoozeOpen]);

  const created = new Date(row.createdAt);
  const dateText = created.toLocaleString("ar-EG", {
    dateStyle: "short",
    timeStyle: "short",
  });

  return (
    <li
      className={cn(
        "group flex items-start gap-3 px-3 sm:px-4 py-3 transition-colors",
        isUnread ? "bg-primary/[0.04]" : "bg-white hover:bg-gray-50",
      )}
    >
      <input
        type="checkbox"
        checked={selected}
        onChange={(e) => onToggleSelect(e.target.checked)}
        className="mt-2 w-4 h-4 shrink-0"
        aria-label="تحديد الإشعار"
      />
      <span
        className="shrink-0 w-10 h-10 rounded-xl flex items-center justify-center"
        style={{ backgroundColor: `${color}18`, color }}
      >
        <NotificationIcon type={row.type} category={row.category} size={18} />
      </span>
      <div className="flex-1 min-w-0">
        <div className="flex items-start gap-2 flex-wrap">
          <p
            className={cn(
              "text-sm flex-1 min-w-0 text-gray-800",
              isUnread && "font-bold",
            )}
          >
            {href ? (
              <Link
                href={href}
                onClick={() => {
                  if (isUnread) onToggleRead();
                }}
                className="hover:underline"
              >
                {row.title}
              </Link>
            ) : (
              row.title
            )}
          </p>
          {row.priority >= 1 && (
            <span
              className={cn(
                "shrink-0 inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-bold",
                row.priority >= 2
                  ? "bg-red-100 text-red-700"
                  : "bg-amber-100 text-amber-700",
              )}
            >
              {PRIORITY_LABEL[Math.min(2, Math.max(0, row.priority))]}
            </span>
          )}
          {isUnread && (
            <span
              className="shrink-0 mt-1.5 w-2 h-2 rounded-full bg-primary"
              aria-label="غير مقروء"
            />
          )}
        </div>
        {row.body && (
          <p className="text-xs text-gray-500 line-clamp-2 mt-0.5">
            {row.body}
          </p>
        )}
        <div className="mt-1.5 flex items-center gap-3 flex-wrap text-[11px] text-gray-400">
          {row.category && CATEGORY_LABELS[row.category as EventCategory] && (
            <span className="inline-flex items-center gap-1">
              {CATEGORY_LABELS[row.category as EventCategory].label}
            </span>
          )}
          <span>·</span>
          <span>{dateText}</span>
          {row.snoozedUntil && new Date(row.snoozedUntil) > new Date() && (
            <span className="inline-flex items-center gap-1 text-amber-600">
              <Clock size={10} /> مؤجل حتى{" "}
              {new Date(row.snoozedUntil).toLocaleTimeString("ar-EG", {
                hour: "2-digit",
                minute: "2-digit",
              })}
            </span>
          )}
        </div>
      </div>
      <div className="shrink-0 flex items-center gap-0.5 opacity-60 group-hover:opacity-100 transition-opacity">
        <button
          onClick={onToggleRead}
          className="tap-44 p-2 rounded-lg hover:bg-white text-gray-500 hover:text-primary"
          title={isUnread ? "تعليم مقروء" : "تعليم غير مقروء"}
          aria-label={isUnread ? "تعليم مقروء" : "تعليم غير مقروء"}
        >
          {isUnread ? <Eye size={14} /> : <EyeOff size={14} />}
        </button>
        <div className="relative" ref={snoozeRef}>
          <button
            onClick={() => setSnoozeOpen((o) => !o)}
            className="tap-44 p-2 rounded-lg hover:bg-white text-gray-500 hover:text-amber-600"
            title="تأجيل"
            aria-label="تأجيل"
            aria-expanded={snoozeOpen}
          >
            <Clock size={14} />
          </button>
          {snoozeOpen && (
            <div className="absolute end-0 top-full mt-1 w-44 bg-white rounded-lg shadow-lg border border-gray-200 z-20 py-1 text-sm">
              {[
                { m: 60, label: "ساعة واحدة" },
                { m: 60 * 4, label: "4 ساعات" },
                { m: 60 * 24, label: "غدًا" },
                { m: 60 * 24 * 7, label: "أسبوع" },
              ].map((opt) => (
                <button
                  key={opt.m}
                  onClick={() => {
                    setSnoozeOpen(false);
                    onSnooze(opt.m);
                  }}
                  className="w-full text-start px-3 py-2 hover:bg-gray-50"
                >
                  {opt.label}
                </button>
              ))}
            </div>
          )}
        </div>
        <button
          onClick={onToggleArchive}
          className="tap-44 p-2 rounded-lg hover:bg-white text-gray-500 hover:text-primary"
          title={isArchived ? "إعادة من الأرشيف" : "أرشفة"}
          aria-label={isArchived ? "إعادة من الأرشيف" : "أرشفة"}
        >
          {isArchived ? <ArchiveRestore size={14} /> : <Archive size={14} />}
        </button>
        <button
          onClick={onDelete}
          className="tap-44 p-2 rounded-lg hover:bg-white text-gray-500 hover:text-red-600"
          title="حذف"
          aria-label="حذف"
        >
          <Trash2 size={14} />
        </button>
      </div>
    </li>
  );
}
